version: '3.7'

services:
  final_project:
    container_name: golang_container
    environment:
     - DBUSER=${DBUSER}
     - DBPASSWORD=${DBPASSWORD}
     - DBHOST=${DBHOST}
     - DBNAME=${DBNAME}
     - DBPORT=${DBPORT}
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/final_project
    depends_on:
      - db
    networks:
      - main

  db:
    image: postgres:15.1
    container_name: postgres_container
    restart: always
    environment:
     - POSTGRES_USER=${DBUSER}
     - POSTGRES_PASSWORD=${DBPASSWORD}     
     - POSTGRES_DB=${DBNAME}
     - DATABASE_HOST=${DBHOST}
     - DATABASE_PORT=${DBPORT}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - main

volumes:
  pg_data:

networks:
  main:
    driver: bridge